# Configuration Base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/server_monitoring_db
spring.datasource.username=postgres
spring.datasource.password=admin123

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port
server.port=8081

# Documentation Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html